#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/shopping
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#  mybatis:
#    type-aliases-package: kr.hs.dgsw.webclass01
#    mapper-locations: mybatis/mapper/**/*.xml